apiVersion: v1
kind: Pod
metadata:
  labels:
    env: test
  name: cinder-client
  namespace: default
spec:
  containers:
  - image: digambarpat/cinder-client:v1.1
    imagePullPolicy: IfNotPresent
    name: cinder-client