kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iscsi-pvc
spec:
  volumeMode: Block
  volumeName: iscsi-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""