apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  volumeMode: "Block"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.189.148:3260
    portals: ['192.168.189.148:3260']
    iqn: iqn.2010-10.org.openstack:volume-da929da9-ce7d-4edf-862e-5d4fe34eefd7
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: True
    chapAuthSession: True
    secretRef:
      name: iscsi-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: iscsi-secret
type: "kubernetes.io/iscsi-chap"
data:
  discovery.sendtargets.auth.username: ZlBOS3FWejZQcU1DM1ZUeXJvdjY=
  discovery.sendtargets.auth.password: ZEFKS1VYYVIzNm5lMnJteg==
  node.session.auth.username: ZlBOS3FWejZQcU1DM1ZUeXJvdjY=
  node.session.auth.password: ZEFKS1VYYVIzNm5lMnJteg==