apiVersion: v1
kind: PersistentVolume
metadata:
  name: hellopv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /dev/mapper/cinder--volumes-volume--aa3aebc1--b34b--4d30--8574--d42e909ee564
